### ISSUE TITLE
I can't find a Team Token 

### ISSUE THREAD

**Issue by dstrickler** [IndigoDomotics/slack-notify#1]
Many thanks for creating this plugin! I'm trying to use it for my family's Slack channel, but I can't find the Team Token. Perhaps that only on the paid Slack version?

**Comment by FlyingDiver** [comment]
Did you read the instructions here:  https://github.com/IndigoDomotics/slack-notify/wiki

**Comment by dstrickler** [comment]
Yes, I did. I think I'm getting confused at "Team Token". Is this a special token for the "Team" as in "Enterprise"? Or is this just a regular token that a non-paying user can get?

When I get to the part in the instructions that talks about getting a Team Token, I can't find how to generate a Team Token. I can't even find anywhere on Slack's help to generate a Team Token.

Thus where I'm stuck.

**Comment by FlyingDiver** [comment]
I think Slack has changed the authentication method used for Webhooks and the plugin won't work as it is.  I'll try to look into that and see if it can be fixed.  The original author abandoned the plugin, so no guarantees.

**Comment by dstrickler** [comment]
Got it - thanks!

**Comment by FlyingDiver** [comment]
I gave up trying to figure out how to use the old plugin.  So I wrote a new one.

https://github.com/FlyingDiver/Indigo-Slack2

Bare bones for now.  If it works for you, and you want more features, create an issue for them on that project.
